name: Download IoTDB 0.12.5

on:
  workflow_dispatch:

jobs:
  pull-and-save:
    runs-on: ubuntu-latest

    steps:
      - name: Pull image
        run: |
          docker pull apache/iotdb:0.12.5-node

      - name: Save image
        run: |
          docker save apache/iotdb:0.12.5-node -o iotdb-0.12.5.tar

      - name: Compress
        run: |
          gzip iotdb-0.12.5.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: iotdb-0.12.5
          path: iotdb-0.12.5.tar.gz
